sudo: false
language: python

python:
  - 3.5
  - 3.4
  - 2.7

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n my-project python=3 pytest
  - source activate my-project
  - pip install tox

script:
    tox

# after_success:
#   - coveralls
